// Data created with Img2CPC - (c) Retroworks - 2007-2017
// Palete constants
#define TITLESCREENFULL_WINCPCTELERA_PALETTE_OFF    0
#define TITLESCREENFULL_WINCPCTELERA_PALETTE_SIZE   0

// Tile titlescreenfull_wincpctelera - 160x200 pixels, 80x200 bytes.
#define TITLESCREENFULL_WINCPCTELERA_OFF        0
#define TITLESCREENFULL_WINCPCTELERA_SIZE       16000
#define TITLESCREENFULL_WINCPCTELERA_W          80
#define TITLESCREENFULL_WINCPCTELERA_H          200
